Repository Team-OMD/Backend, pull requests merged in 2024-05, with the labels that each got.

#42 [Feat/#40] 게시물 조회 시 좋아요 여부 추가로 반환
  src/main/java/com/onmydesk/backend/post/controller/PostController.java
  src/main/java/com/onmydesk/backend/post/dto/PostAndProductResponse.java
  src/main/java/com/onmydesk/backend/post/dto/PostResponse.java
  src/main/java/com/onmydesk/backend/post/mapper/PostMapper.java
  src/main/java/com/onmydesk/backend/post/service/PostService.java
Labels: 기능구현

#43 [Feat/#41] 상품 찜 구현
  src/main/java/com/onmydesk/backend/error/errorcode/WishErrorCode.java
  src/main/java/com/onmydesk/backend/post/service/PostService.java
  src/main/java/com/onmydesk/backend/product/controller/ProductController.java
  src/main/java/com/onmydesk/backend/product/domain/Product.java
  src/main/java/com/onmydesk/backend/product/dto/ProductInfoResponse.java
  src/main/java/com/onmydesk/backend/product/dto/ProductResponse.java
  src/main/java/com/onmydesk/backend/product/mapper/ProductMapper.java
  src/main/java/com/onmydesk/backend/product/repository/ProductRepository.java
  src/main/java/com/onmydesk/backend/product/service/ProductService.java
  src/main/java/com/onmydesk/backend/wish/controller/WishController.java
  src/main/java/com/onmydesk/backend/wish/domain/Wish.java
  src/main/java/com/onmydesk/backend/wish/repository/WishRepository.java
  src/main/java/com/onmydesk/backend/wish/service/WishService.java
Labels: 기능구현

#46 [Feat/#45] 찜한 상품 조회
  src/main/java/com/onmydesk/backend/member/controller/MemberController.java
  src/main/java/com/onmydesk/backend/product/domain/Product.java
  src/main/java/com/onmydesk/backend/product/repository/ProductRepository.java
  src/main/java/com/onmydesk/backend/product/service/ProductService.java
Labels: 기능구현

#50 [Feat/#49] AWS 이미지 업로드 및 썸네일 지정 로직 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/onmydesk/backend/BackendApplication.java
  src/main/java/com/onmydesk/backend/post/controller/PostController.java
  src/main/java/com/onmydesk/backend/post/domain/Post.java
  src/main/java/com/onmydesk/backend/post/dto/PostRequest.java
  src/main/java/com/onmydesk/backend/post/dto/PostResponse.java
  src/main/java/com/onmydesk/backend/post/mapper/PostMapper.java
  src/main/java/com/onmydesk/backend/post/service/PostService.java
  src/main/java/com/onmydesk/backend/s3/S3Config.java
  src/main/java/com/onmydesk/backend/s3/S3Uploader.java
  src/main/java/com/onmydesk/backend/s3/controller/ImageController.java
  src/main/java/com/onmydesk/backend/s3/domain/Image.java
  src/main/java/com/onmydesk/backend/s3/repository/ImageRepository.java
  src/main/resources/application.yml
Labels: 기능구현

#54 [Feat/#51] 로그아웃 구현
  Dockerfile.dev
  build.gradle
  docker-compose.dev.yml
  docker-compose.yml
  src/main/java/com/onmydesk/backend/config/redis/RedisConfig.java
  src/main/java/com/onmydesk/backend/config/security/CorsConfig.java
  src/main/java/com/onmydesk/backend/config/security/SecurityConfig.java
  src/main/java/com/onmydesk/backend/config/security/SecurityUtil.java
  src/main/java/com/onmydesk/backend/jwt/JwtFilter.java
  src/main/java/com/onmydesk/backend/jwt/JwtSecurityConfig.java
  src/main/java/com/onmydesk/backend/jwt/TokenProvider.java
  src/main/java/com/onmydesk/backend/member/controller/MemberController.java
  src/main/java/com/onmydesk/backend/member/dto/TokenRequestDto.java
  src/main/java/com/onmydesk/backend/member/dto/TokenResponseDto.java
  src/main/java/com/onmydesk/backend/member/service/MemberService.java
  src/main/java/com/onmydesk/backend/post/controller/PostController.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 기능구현, 오류수정

#53 [Feat/#52] 상품 크롤링 수정
  src/main/java/com/onmydesk/backend/error/errorcode/ProductErrorCode.java
  src/main/java/com/onmydesk/backend/product/controller/ProductController.java
  src/main/java/com/onmydesk/backend/product/domain/Page.java
  src/main/java/com/onmydesk/backend/product/domain/Product.java
  src/main/java/com/onmydesk/backend/product/dto/PageRequest.java
  src/main/java/com/onmydesk/backend/product/dto/ProductRequest.java
  src/main/java/com/onmydesk/backend/product/mapper/PageMapper.java
  src/main/java/com/onmydesk/backend/product/service/ProductSearchAndCrawlingService.java
  src/main/java/com/onmydesk/backend/product/service/ProductSearchService.java
  src/main/java/com/onmydesk/backend/product/service/ProductService.java
Labels: 리팩토링

#56 [Fix/#55] 상품 이름 HTML 태그 수정
  src/main/java/com/onmydesk/backend/product/service/ProductSearchAndCrawlingService.java
Labels: 오류수정

#60 [Fix/#59] 로그아웃시 access, refresh 토큰 둘 다 유효할 때만 가능하도록 수정
  src/main/java/com/onmydesk/backend/error/errorcode/MemberErrorCode.java
  src/main/java/com/onmydesk/backend/jwt/TokenProvider.java
  src/main/java/com/onmydesk/backend/member/service/MemberService.java
  src/main/java/com/onmydesk/backend/post/controller/PostController.java
Labels: 오류수정

#62 [Refactor/#57] JPA 조회 성능 최적화
  src/main/java/com/onmydesk/backend/heart/domain/Heart.java
  src/main/java/com/onmydesk/backend/post/controller/PostController.java
  src/main/java/com/onmydesk/backend/post/dto/PostPreviewResponse.java
  src/main/java/com/onmydesk/backend/post/mapper/PostMapper.java
  src/main/java/com/onmydesk/backend/post/repository/PostProductRepository.java
  src/main/java/com/onmydesk/backend/post/repository/PostRepository.java
  src/main/java/com/onmydesk/backend/post/service/PostService.java
  src/main/resources/application.yml
Labels: 리팩토링

#65 [Fix] 이미지 업데이트 안 되는 거 수정
  src/main/java/com/onmydesk/backend/post/dto/PostAndProductResponse.java
  src/main/java/com/onmydesk/backend/post/service/PostService.java
Labels: 오류수정

#67 [Fix] imageUrls 수정 후 조회 Null 값으로 나오는 거 수정
  src/main/java/com/onmydesk/backend/post/service/PostService.java
Labels: 오류수정

#69 [Refactor/#68] 상품 검색 기능 수정
  src/main/java/com/onmydesk/backend/product/service/ProductSearchAndCrawlingService.java
Labels: 리팩토링

#71 [Refactor/#70] 셋업 상품 삭제 수정
  src/main/java/com/onmydesk/backend/setup/controller/SetupController.java
  src/main/java/com/onmydesk/backend/setup/repository/SetupProductRepository.java
  src/main/java/com/onmydesk/backend/setup/service/SetupService.java
Labels: 리팩토링

#73 [Refactor/#72] 셋업 상품 삭제 postTotalPrice 수정
  src/main/java/com/onmydesk/backend/setup/domain/Setup.java
  src/main/java/com/onmydesk/backend/setup/service/SetupService.java
Labels: 리팩토링

#74 [Feat/#66] 최근 인기 게시글 목록 조회
  build.gradle
  src/main/java/com/onmydesk/backend/BackendApplication.java
  src/main/java/com/onmydesk/backend/config/redis/RedisConfig.java
  src/main/java/com/onmydesk/backend/config/redis/RedisUtil.java
  src/main/java/com/onmydesk/backend/heart/repository/HeartRepository.java
  src/main/java/com/onmydesk/backend/post/controller/PostController.java
  src/main/java/com/onmydesk/backend/post/dto/PostPreviewResponse.java
  src/main/java/com/onmydesk/backend/post/service/PopularPost.java
Labels: 기능구현
